//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCars : BaseEntity
    {

        public long WechatUserID { get; set; }
        public string Attribution { get; set; }
        public string CarType { get; set; }
        public string CarNO { get; set; }
        public string CarOwnerName { get; set; }
        public string CarOwnerTel { get; set; }
        public Nullable<System.DateTime> InsuranceTime { get; set; }
        public string Note { get; set; }

    }
}
